name: HTML Validation

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tidy
        run: sudo apt-get update && sudo apt-get install -y tidy
      - name: Run HTML test
        run: make test
